import type { Product, Category, Review, FAQItem } from '@/types'

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Organizadores', slug: 'organizadores', icon: 'briefcase', productCount: 8 },
  { id: '2', name: 'Porta Pasaportes', slug: 'porta-pasaportes', icon: 'identification-card', productCount: 5 },
  { id: '3', name: 'Neceseres', slug: 'neceseres', icon: 'drop', productCount: 6 },
  { id: '4', name: 'Scrunchies', slug: 'scrunchies', icon: 'sparkle', productCount: 4 },
  { id: '5', name: 'Accesorios Vuelo', slug: 'accesorios-vuelo', icon: 'airplane-tilt', productCount: 5 },
  { id: '6', name: 'Equipaje', slug: 'equipaje', icon: 'scales', productCount: 3 },
  { id: '7', name: 'Biblioteca Viajera', slug: 'biblioteca-viajera', icon: 'book-open', productCount: 4 },
  { id: '8', name: 'Kits Viajeros', slug: 'kits', icon: 'gift', productCount: 6 },
]

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Set Organizadores de Maleta x6',
    slug: 'set-organizadores-maleta-x6',
    description: 'El set definitivo para viajeras organizadas. 6 cubos de compresión en diferentes tamaños para organizar ropa, accesorios y más. Perfectos para tu maleta y también para el día a día. Fabricados en tela resistente al agua con cremallera suave.',
    price: 18900,
    compareAtPrice: 24900,
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
      'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&q=80',
    ],
    category: 'Organizadores',
    categorySlug: 'organizadores',
    stock: 15,
    featured: true,
    isNew: false,
    rating: 4.9,
    reviewCount: 127,
    sku: 'ORG-001',
    tags: ['organizador', 'maleta', 'viaje', 'set'],
    variants: [
      { id: 'v1', name: 'Color', value: 'Rosa', stock: 10 },
      { id: 'v2', name: 'Color', value: 'Azul celeste', stock: 5 },
    ],
  },
  {
    id: '2',
    name: 'Porta Pasaporte Girly Premium',
    slug: 'porta-pasaporte-girly-premium',
    description: 'El porta pasaporte que combina con tu estilo. Con bolsillos para tarjetas, documentos y un espacio secreto para billetes. Diseño floral bordado exclusivo de Muy Viajeras. Para tus viajes y tu día a día',
    price: 9900,
    images: [
      'https://images.unsplash.com/photo-1621072156002-e2fccdc0b176?w=600&q=80',
      'https://images.unsplash.com/photo-1584464491033-06628f3a6b7e?w=600&q=80',
    ],
    category: 'Porta Pasaportes',
    categorySlug: 'porta-pasaportes',
    stock: 32,
    featured: true,
    isNew: true,
    rating: 4.8,
    reviewCount: 89,
    sku: 'PP-001',
    tags: ['pasaporte', 'porta pasaporte', 'girly', 'viaje'],
    variants: [
      { id: 'v1', name: 'Color', value: 'Rosa floral', stock: 20 },
      { id: 'v2', name: 'Color', value: 'Beige arena', stock: 12 },
    ],
  },
  {
    id: '3',
    name: 'Neceser Maquillaje Transparente',
    slug: 'neceser-maquillaje-transparente',
    description: 'Pasa el control de seguridad sin quitarte el estrés. Neceser transparente tamaño carry-on con compartimentos organizados y asa superior. Todo tu makeup siempre a la vista y organizado ',
    price: 12900,
    compareAtPrice: 15900,
    images: [
      'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&q=80',
    ],
    category: 'Neceseres',
    categorySlug: 'neceseres',
    stock: 20,
    featured: true,
    isNew: false,
    rating: 4.7,
    reviewCount: 64,
    sku: 'NEC-001',
    tags: ['neceser', 'maquillaje', 'transparente', 'viaje'],
  },
  {
    id: '4',
    name: 'Scrunchie con Bolsillo Secreto',
    slug: 'scrunchie-bolsillo-secreto',
    description: 'El accesorio más inteligente del mercado. Lleva tu efectivo, tarjetas o llaves escondidas en tu coleta. Disponible en colores pastel y con brillitos. Funcional, lindo y súper cómodo',
    price: 4900,
    images: [
      'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&q=80',
    ],
    category: 'Scrunchies',
    categorySlug: 'scrunchies',
    stock: 45,
    featured: false,
    isNew: true,
    rating: 4.9,
    reviewCount: 203,
    sku: 'SCR-001',
    tags: ['scrunchie', 'bolsillo', 'accesorio', 'cabello'],
    variants: [
      { id: 'v1', name: 'Color', value: 'Rosa pastel', stock: 15 },
      { id: 'v2', name: 'Color', value: 'Lila', stock: 15 },
      { id: 'v3', name: 'Color', value: 'Turquesa', stock: 15 },
    ],
  },
  {
    id: '5',
    name: 'Almohada de Viaje Rellenable',
    slug: 'almohada-viaje-rellenable',
    description: 'Los vuelos largos nunca más serán un suplicio. Almohada inflable con funda de tela suave, compacta cuando está desinflada. Se guarda en su propia bolsita. Perfecta para avión, bus o tren',
    price: 8900,
    images: [
      'https://images.unsplash.com/photo-1584461611869-f30bc3d3d8a8?w=600&q=80',
    ],
    category: 'Accesorios Vuelo',
    categorySlug: 'accesorios-vuelo',
    stock: 18,
    featured: true,
    isNew: false,
    rating: 4.6,
    reviewCount: 47,
    sku: 'ALM-001',
    tags: ['almohada', 'viaje', 'vuelo', 'comodidad'],
    variants: [
      { id: 'v1', name: 'Color', value: 'Rosa', stock: 10 },
      { id: 'v2', name: 'Color', value: 'Gris perla', stock: 8 },
    ],
  },
  {
    id: '6',
    name: 'Pesa Maletas Digital Rosa',
    slug: 'pesa-maletas-digital-rosa',
    description: 'No más sorpresas en el aeropuerto. Pesa tu maleta con precisión antes de partir. Pantalla LED, batería incluida, mide hasta 50kg. En el color más bonito del mercado.',
    price: 7900,
    images: [
      'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&q=80',
    ],
    category: 'Equipaje',
    categorySlug: 'equipaje',
    stock: 25,
    featured: false,
    isNew: false,
    rating: 4.8,
    reviewCount: 156,
    sku: 'PES-001',
    tags: ['pesa maletas', 'digital', 'equipaje', 'viaje'],
  },
  {
    id: '7',
    name: 'Kit Viajera Completo — La Esencial',
    slug: 'kit-viajera-completo-esencial',
    description: 'TODO lo que necesitas para tu próximo viaje en un solo pack. Incluye: set organizadores x4, porta pasaporte, neceser pequeño y pesa maletas. Literal, te llevas todo listo sin tener que pensar ¡Ahorra un 20%!',
    price: 34900,
    compareAtPrice: 44600,
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    ],
    category: 'Kits Viajeros',
    categorySlug: 'kits',
    stock: 10,
    featured: true,
    isNew: false,
    rating: 5.0,
    reviewCount: 38,
    sku: 'KIT-001',
    tags: ['kit', 'combo', 'pack', 'set completo', 'regalo'],
  },
  {
    id: '8',
    name: 'Tag Equipaje Personalizable',
    slug: 'tag-equipaje-personalizable',
    description: 'Identifica tu maleta con estilo y sin confusiones. Tag de cuero vegano con ventana para tus datos y diseño floral exclusivo. Porque tu maleta también merece ser bonita',
    price: 3900,
    images: [
      'https://images.unsplash.com/photo-1521791055366-0d553872952f?w=600&q=80',
    ],
    category: 'Equipaje',
    categorySlug: 'equipaje',
    stock: 60,
    featured: false,
    isNew: true,
    rating: 4.7,
    reviewCount: 82,
    sku: 'TAG-001',
    tags: ['tag', 'equipaje', 'maleta', 'identificador'],
    variants: [
      { id: 'v1', name: 'Color', value: 'Rosa', stock: 30 },
      { id: 'v2', name: 'Color', value: 'Beige', stock: 30 },
    ],
  },
  {
    id: '9',
    name: 'Diario de Viaje Floral',
    slug: 'diario-de-viaje-floral',
    description: 'Registra cada aventura en este diario de tapa dura con diseño floral exclusivo. Páginas para itinerarios, mapas, recuerdos y notas. El compañero perfecto para documentar tus viajes con estilo.',
    price: 11900,
    compareAtPrice: 14900,
    images: [
      'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=600&q=80',
      'https://images.unsplash.com/photo-1517842645767-c639042777db?w=600&q=80',
    ],
    category: 'Biblioteca Viajera',
    categorySlug: 'biblioteca-viajera',
    stock: 22,
    featured: true,
    isNew: true,
    rating: 4.9,
    reviewCount: 58,
    sku: 'BIB-001',
    tags: ['diario', 'viaje', 'journal', 'libreta'],
    variants: [
      { id: 'v1', name: 'Color', value: 'Rosa floral', stock: 12 },
      { id: 'v2', name: 'Color', value: 'Crema', stock: 10 },
    ],
  },
  {
    id: '10',
    name: 'Planner de Viajes Semanal',
    slug: 'planner-de-viajes-semanal',
    description: 'Organiza cada detalle de tu próxima escapada. Checklists de equipaje, presupuesto, reservas y plan día a día. Diseño minimalista y femenino que cabe perfecto en tu cartera.',
    price: 9900,
    images: [
      'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=600&q=80',
    ],
    category: 'Biblioteca Viajera',
    categorySlug: 'biblioteca-viajera',
    stock: 30,
    featured: false,
    isNew: false,
    rating: 4.8,
    reviewCount: 41,
    sku: 'BIB-002',
    tags: ['planner', 'organizador', 'viaje', 'agenda'],
  },
  {
    id: '11',
    name: 'Set de Stickers Viajera',
    slug: 'set-de-stickers-viajera',
    description: 'Personaliza tu diario, maleta o laptop con 50 stickers de destinos, aviones, mapas y frases viajeras. Vinilo resistente al agua, perfectos para decorar y marcar tus aventuras.',
    price: 4900,
    compareAtPrice: 6900,
    images: [
      'https://images.unsplash.com/photo-1600195077909-46e573870d99?w=600&q=80',
    ],
    category: 'Biblioteca Viajera',
    categorySlug: 'biblioteca-viajera',
    stock: 45,
    featured: false,
    isNew: true,
    rating: 4.7,
    reviewCount: 96,
    sku: 'BIB-003',
    tags: ['stickers', 'decoración', 'viaje', 'scrapbook'],
  },
  {
    id: '12',
    name: 'Guía de Bolsillo del Viajero',
    slug: 'guia-de-bolsillo-del-viajero',
    description: 'Tips, frases en varios idiomas, conversor de monedas y checklist esencial en un formato compacto. Hecha por viajeras para viajeras, con todo lo que ojalá hubieras sabido en tu primer viaje.',
    price: 7900,
    images: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80',
    ],
    category: 'Biblioteca Viajera',
    categorySlug: 'biblioteca-viajera',
    stock: 18,
    featured: true,
    isNew: false,
    rating: 5.0,
    reviewCount: 33,
    sku: 'BIB-004',
    tags: ['guía', 'libro', 'tips', 'viaje'],
  },
]

export const REVIEWS: Review[] = [
  {
    id: '1',
    author: 'Camila Torres',
    rating: 5,
    comment: 'Los organizadores son una maravilla! Llegaron súper rápido y la calidad es increíble. Mi maleta nunca había estado tan ordenada. 100% recomiendo a Muy Viajeras',
    productId: '1',
    verified: true,
    createdAt: '2026-05-15',
    avatar: 'https://i.pravatar.cc/100?img=1',
  },
  {
    id: '2',
    author: 'Javiera López',
    rating: 5,
    comment: 'El porta pasaporte es hermoso, exactamente como en las fotos. Lo uso todos los días aunque no esté viajando jaja. El despacho llegó en 2 días a Valparaíso.',
    productId: '2',
    verified: true,
    createdAt: '2026-05-28',
    avatar: 'https://i.pravatar.cc/100?img=2',
  },
  {
    id: '3',
    author: 'Ana García',
    rating: 5,
    comment: 'Compré el kit completo para mi viaje a Europa y fue la mejor decisión. Todo llegó perfecto y muy bien empaquetado con su bolsita rosada. Muy Viajeras es lo mejor.',
    productId: '7',
    verified: true,
    createdAt: '2026-06-01',
    avatar: 'https://i.pravatar.cc/100?img=3',
  },
  {
    id: '4',
    author: 'Valentina Muñoz',
    rating: 5,
    comment: 'El scrunchie con bolsillo secreto es GENIAL. Lo uso en el aeropuerto para guardar el efectivo y me da una tranquilidad enorme. Ya le compré a todas mis amigas.',
    productId: '4',
    verified: true,
    createdAt: '2026-06-10',
    avatar: 'https://i.pravatar.cc/100?img=5',
  },
  {
    id: '5',
    author: 'Sofía Reyes',
    rating: 5,
    comment: 'Primera compra y quedé encantada. La atención es súper cercana, respondieron mis dudas al tiro. Los productos son lindísimos y de buena calidad. Volveré a comprar!',
    productId: '3',
    verified: true,
    createdAt: '2026-06-18',
    avatar: 'https://i.pravatar.cc/100?img=7',
  },
]

export const FAQ_ITEMS: FAQItem[] = [
  {
    question: '¿Cuánto demora el envío?',
    answer: 'Los pedidos se despachan en 1-2 días hábiles. La entrega por Blue Express tarda entre 2-5 días hábiles según tu región. Recibirás un email con el número de seguimiento en cuanto tu pedido sea enviado.',
  },
  {
    question: '¿Cuál es el costo de envío?',
    answer: 'El envío tiene un costo de $3.990 a todo Chile. ¡Envío GRATIS en compras sobre $25.000! También puedes retirar gratis en Ñuñoa, Santiago.',
  },
  {
    question: '¿Cómo puedo pagar?',
    answer: 'Aceptamos tarjeta de crédito y débito (Visa, Mastercard), MercadoPago y transferencia bancaria. Pronto también cuotas sin interés.',
  },
  {
    question: '¿Puedo retirar en Santiago?',
    answer: '¡Sí! Puedes retirar en Ñuñoa, Santiago, sin costo adicional. Coordinaremos el horario de retiro por WhatsApp o email.',
  },
  {
    question: '¿Qué pasa si mi producto llega dañado?',
    answer: 'Si tu producto llega dañado o defectuoso, lo reponemos. Punto. Contáctanos dentro de 48 horas de recibir tu pedido con fotos del producto y te solucionamos al tiro',
  },
  {
    question: '¿Puedo cambiar o devolver un producto?',
    answer: 'Aceptamos cambios dentro de 10 días de recibido el pedido, siempre que el producto esté sin uso y con su empaque original. Escríbenos por WhatsApp o Instagram y coordinamos.',
  },
]

export const FREE_SHIPPING_THRESHOLD = 25000
export const SHIPPING_COST = 3990
